### PR TITLE
writable-paths: add /var/lib/dhcpcd writable-paths for datasource discovery

### PR DESCRIPTION
**Pull request by blackboxsw**
If dhcpcd is installed in a cloud image, cloud-init may attempt early datasource discovery using dhcpcd in order to get information about active instance metadata service IP addresses and routes. The dhcpcd client writes out leases which cloud-init parses under /var/lib/dhcpcd.

Add this support so cloud-init can detect network-bound datasources such as Azure, Ec2 and GCE.

### CODE REVIEW

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM, thank you

**Comment by alfonsosanchezbeato** [comment]
@blackboxsw would you mind proposing also to the `core24` branch? We already forked.

**Comment by blackboxsw** [comment]
Thanks @alfonsosanchezbeato. reset the root upstream/core24 and rebased my changeset on top.

**Comment by alfonsosanchezbeato** [comment]
@blackboxsw please propose also to main branch

**Comment by blackboxsw** [comment]
> @blackboxsw please propose also to main branch

Thanks @alfonsosanchezbeato just pushed https://github.com/canonical/core-base/pull/237 for a PR against main as well.

**Pull request merged**
